### ISSUE TITLE
Fail to save song in Solonus

### ISSUE THREAD

**Issue by lyh543-autra** [SonolusHaniwa/sonolus-server-cpp#11]
**Describe the bug**
Fail to save song in Solonus. See screenshots.

**To Reproduce**
1. Go to song detail page.
2. Click on 'Save'.
3. Click any Collection to save the song.
4. See error as screenshots.

**Expected behavior**
Successfully save song.

**Screenshots**
![09568bf23c1492cdc6047b9a3ffb8428](https://github.com/SonolusHaniwa/sonolus-server-cpp/assets/117634067/8e734085-5b91-429b-ad0c-0e3ced97121a)
![f82a25e8c6eb08c943b51246388f05e2](https://github.com/SonolusHaniwa/sonolus-server-cpp/assets/117634067/60de751e-8678-40ba-948e-76b091856ecf)

**Smartphone (please complete the following information):**
- Android [13]
 - Solonus [0.7.5(1) Beta]

**Additional context**

**Comment by LittleYang0531** [comment]
Fixed. You can try it in Sonolus.

If there any other issues, reopen this issue and report it. 😊

**Comment by lyh543** [comment]
Thanks!
