### ISSUE TITLE
Featuring in Sonolus Wiki

### ISSUE THREAD

**Issue by NonSpicyBurrito** [SonolusHaniwa/sonolus-server-cpp#8]
Would this project like to be featured in Sonolus Wiki? Specifically on page [Custom Server Specs/Frameworks and Tools](https://wiki.sonolus.com/custom-server-specs/frameworks-and-tools.html).

**Comment by LittleYang0531** [comment]
Thanks for your reply.

This project was developed entirely accroding to Custom Server Spec, and many other useful endpoints have been added to it. If this project is qualified to be featured on this page, I would very happy to that.

**Comment by NonSpicyBurrito** [comment]
Perfect, added with https://github.com/Sonolus/wiki-custom-server-specs/pull/20

**Comment by LittleYang0531** [comment]
Thanks
